#! /usr/bin/env python
#
#  Note: run this command from the root data directory
#
#      this script will sync (from a selected set of methods)
#      all files in this directory tree listed in files.lis
#  
# root-link/url/dir
#
# methods:
#      wget    wget           http://blabla/
#      curl
#      ln-s    soft link
#      ln      hard link
#      rsync
#      scp
#
import sys, os, errno, fnmatch


_debug = True


# the follow two parameters can be defaulted via a parameter file, 
# grabdata.ini, in the current directory, or the same directory as
# grabdata, in that order
#

# url:  (and some examples)
url = "http://foo.bar/"
url = '/home/teuben/ADMIT/ALMAvis/astute/data'

# method: (and some examples)
method = "ln-s"

def query_dir(here=None,fn="files.lis"):
    """
    from here, drill down and find directories in which ADMIT exists
    """
    dlist = []
    if here == None:
        path = "."
    else:
        path = here
    n = 0
    for path, dirs, files in os.walk(path):
        # better not to loop, but os.path() for existence
        n = n + 1
        for f in files:
            if f == fn: dlist.append(path)
    if _debug: print "Queried ",n," directories, found ",len(dlist), " with ",fn
    return dlist


def find_files(pattern="files.lis"):
    """
    Find files containing a wildcard pattern
    """
    flist = []
    for file in os.listdir('.'):
        if fnmatch.fnmatch(file,pattern):
            flist.append(file)
    return flist



fn = "files.lis"
dirs = query_dir(fn=fn)

for d in dirs:
    print "%s/%s/%s" % (url,d,fn)
